project_id = "pxhpfmdalumfrvnqqrys"

[functions.send-contact-email]
verify_jwt = false

[functions.chat-assistant]
verify_jwt = false

[functions.send-chat-transcript]
verify_jwt = false

[functions.send-exit-popup-email]
verify_jwt = false
